theme: minima
author: Stephen Cresswell

github_username: cressie176
linkedin_username: stephencresswell

plugins:
  - jekyll-redirect-from
  - jekyll-default-layout

defaults:
  - scope:
      path: ""
    values:
      layout: "home"
